services:
  - type: web
    name: mait-it-library-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://abhinav:abhi1111@cluster0.kmbqldx.mongodb.net/smartcampus?appName=Cluster0
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        value: maititlibrary@gmail.com
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://library-website-hazel.vercel.app
